config/routes.rb
Rails.application.routes.draw do
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  get "/contacts" => 'contacts#new', as: :contact
  
  resources :contacts, only: [:new, :create]
  devise_for :accounts
  resources :properties
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :properties


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :subject, :validate => true
  attribute :message,   :validate => true
  

  def headers
    {
      :subject => "Cosy-homes support ticket",
      :to => "cosyhomes@hotmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/property.rb
class Property < ApplicationRecord
	belongs_to :account

	scope :latest, -> { order created_at: :desc }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:update, keys: [:first_name, :last_name, :url])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 def new 
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
  redirect_to root_path, notice: 'Message sent successfully'
    else
      flash.now[:error] = 'Cannot send message'
      render :new
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def properties
  end

  def reports
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new, :create, :destroy]
  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:name, :address, :price, :rooms, :bathrooms, :photo, :photo_cache)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper

  def property_thumbnail property
  	img = property.photo.present? ? property.photo.thumb.url : "placeholder.png"
  	image_tag img, class: "property-thumb"
  end
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/contacts/create.html.erb
<div>
  <% flash.each do |key, value| %>
    <div>
      <a href="#" data-dismiss="alert">×</a>
        <%= value %>
    </div>
  <% end %>
</div>

app/views/contacts/new.html.erb
<section class="form-auth text-center">
  <%= form_for @contact do |f| %>
    <h1 class="h3 mb-3 font-weight-normal">Send Email</h1>
    <% if flash[:error].present? %>
        <p> flash[:error]</p>
    <% end %>
    <%= f.text_field :name, class: "form-control", placeholder: "Full Name" %>

    <br>
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>

    <br>

    <%= f.text_field :subject, class: "form-control", placeholder: "Subject" %>
    
    <br>
    <%= f.text_area :message, class: "form-control", placeholder: "Message" %>

    <br>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Send Email</button>
 
  <% end %>

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
  <h1 class="h3">Dashboard</h1>
  <h2 class="h4" > Previous Listings </h2>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group me-2">
      <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
      <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
    </div>
    <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
      This week
    </button>
  </div>
</div>


<div class="table-responsive">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Price</th>
        <th>Rooms</th>
        <th>Bathrooms</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>3 bedroom medium sized house</td>
        <td>123 Ridgeview Street</td>
        <td>£600,000</td>
        <td>3</td>
        <td>2</td>
      </tr>
      <tr>
        <td>5 bedroom large house</td>
        <td>2 The Hills</td>
        <td>£2,500,000</td>
        <td>5</td>
        <td>5</td>
      </tr>
      <tr>
        <td>1 bedroom studio apartment</td>
        <td>15th Street W</td>
        <td>£1,500,000</td>
        <td>1</td>
        <td>1</td>   
      </tr>
    </tbody>
  </table>
</div>
</main>
</div>
</div>

app/views/dashboard/properties.html.erb
<h1>Dashboard#properties</h1>
<p>Find me in app/views/dashboard/properties.html.erb</p>

app/views/dashboard/reports.html.erb
<h1>Dashboard#reports</h1>
<p>Find me in app/views/dashboard/reports.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="container">
      <p>&copy; Cosy Homes 2020</p>
    </footer>

app/views/layouts/_validation.html.erb
<% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CosyHomes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body id="<%= controller.controller_name %>" class="<%= controller.action_name %>">
    <% if ["public","devise","sessions","registrations","contacts","passwords"].include?(controller.controller_name) %>
    <header>
      <%= render "layouts/nav/public" %>
      <%= yield %>
    </header>
    <% else %>
      <%= render "layouts/nav/dashboard" %>
    
    <div class="container-fluid">
      <div class="row">
        <%= render "layouts/nav/sidebar" %>
        <main class="col-md-9 ml-sm-auto col-lg-10 px-4 mt-3">
          <%= yield %>
        </main>
      </div>
    </div>
    <% end %>


    <%#= render "layouts/footer" %>

    <div id="notifications"><%= notice %></div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js" integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g==" crossorigin="anonymous"></script>
    <script>feather.replace()</script>
  </body>
</html>

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">Cosy Homes</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out", destroy_account_session_path, method: :delete, class: "nav-link" %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Cosy Homes</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <% if account_signed_in? %>
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
            <% else %>
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to "Contact Us", contacts_path, class: "nav-link" %>
          </li>
          <% if account_signed_in? %>
          <li class="nav-item">
            <%= link_to "Log out", destroy_account_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_account_registration_path, class: "nav-link" %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <%= link_to dashboard_path, class: "nav-link" do %>
              <i data-feather="home"></i>
              Listings
            <% end %>      
          </li>
          <li class="nav-item">
            <%= link_to properties_path, class: "nav-link" do %>
              <i data-feather="package"></i>
              Create/View Properties
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link" do %>
              <i data-feather="corner-down-left"></i>
              Return to Home
          <% end %>
  
        </ul>

       
        </ul>
      </div>
    </nav>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <%= render "layouts/validation", item: @property %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :rooms %>
    <%= form.number_field :rooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Save Property", class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1 class="h3">Editing Property</h1>

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.price %></td>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @property.rooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @property.bathrooms %>
</p>

<%= link_to 'Edit Property', edit_property_path(@property), class: "btn btn-success" %>